---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5.1
before_install:
  - gem install bundler -v 1.16.3
  - sudo add-apt-repository ppa:chris-lea/libsodium -y
  - sudo apt-get install -y libsodium-dev
addons:
  apt:
    sources:
    - sourceline: 'ppa:chris-lea/libsodium'
    - sourceline: 'deb http://ppa.launchpad.net/chris-lea/libsodium/ubuntu trusty main'
    - sourceline: 'deb-src http://ppa.launchpad.net/chris-lea/libsodium/ubuntu trusty main'
      update: true
script: bundle exec rake