---
dist: xenial
language: ruby
sudo: required
cache:
  bundler: true
  directories:
  - $HOME/.opam
  - liquidity
rvm:
  - 2.5.1
env:
  - OPAMYES=1
before_install:
  - sh travis-scripts/prepare-ubuntu.sh
  - sh travis-scripts/install-opam.sh
  - sh travis-scripts/install-liquidity.sh
  - gem install bundler -v 1.16.3
script:
  - eval `opam config env`
  - bundle install
  - bundle exec rake