---
service:
  - docker
dist: xenial
language: ruby
sudo: required
cache:
  bundler: true
  directories:
  - $HOME/.opam
rvm:
  - 2.5.1
before_install:
  - sh travis-scripts/prepare-ubuntu.sh
  - docker pull moneytrack/liquidity:babylonnet
  - id=$(docker create moneytrack/liquidity:babylonnet)
  - docker cp $id:/home/opam/.opam/4.07/bin/liquidity - > liquidity
  - chmod +x liquidity
  - gem install bundler -v 1.16.3
script:
  - bundle install
  - bundle exec rake
